import '@ant-design/v5-patch-for-react-19';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { App, ConfigProvider } from 'antd';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import NotificationProvider from '@/context/NotificationProvider';
import { AuthProvider } from '@/context/AuthProvider';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const antdTheme = {
  token: {
    fontFamily: 'var(--font-inter), sans-serif',
    borderRadius: 10,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${inter.variable} antialiased`}>
        <AntdRegistry>
          <ConfigProvider theme={antdTheme}>
            <App>
              <NotificationProvider>
                <AuthProvider>{children}</AuthProvider>
              </NotificationProvider>
            </App>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
